a = input('Digite alguma coisa:')
print('o tipo primitivo desse valor é igual a:', type(a))
print('Só tem espaços??', a.isspace())
print('É um número?', a.isnumeric()) 
print('É alfabético?', a.isalpha())
print('É alfanumérico', a.isalnum())
print('É minuscula?', a.islower())
print('É maiuscula', a.isupper())
print('Está captalizada?', a.istitle())
